// cities.js
export const cities = [
  { label: 'New York (JFK)', value: 'John F. Kennedy International Airport' },
  { label: 'New York (EWR)', value: 'Newark Liberty International Airport' },
  { label: 'Los Angeles (LAX)', value: 'Los Angeles International Airport' },
  { label: 'Chicago (ORD)', value: 'O Hare International Airport' },
  { label: 'Houston (IAH)', value: 'George Bush Intercontinental Airport' },
  { label: 'Phoenix (PHX)', value: 'Phoenix Sky Harbor International Airport' },
  { label: 'Philadelphia (PHL)', value: 'Philadelphia International Airport' },
  { label: 'San Antonio (SAT)', value: 'San Antonio International Airport' },
  { label: 'San Diego (SAN)', value: 'San Diego International Airport' },
  { label: 'Dallas (DFW)', value: 'Dallas/Fort Worth International Airport' },
  { label: 'San Jose (SJC)', value: 'Norman Y. Mineta San Jose International Airport' },
  // Major cities from Europe
  { label: 'London (LHR)', value: 'Heathrow Airport' },
  { label: 'London (LGW)', value: 'Gatwick Airport' },
  { label: 'Paris (CDG)', value: 'Charles de Gaulle Airport' },
  { label: 'Berlin (BER)', value: 'Berlin Brandenburg Airport' },
  { label: 'Madrid (MAD)', value: 'Adolfo Suárez Madrid–Barajas Airport' },
  { label: 'Rome (FCO)', value: 'Leonardo da Vinci–Fiumicino Airport' },
  { label: 'Vienna (VIE)', value: 'Vienna International Airport' },
  { label: 'Amsterdam (AMS)', value: 'Amsterdam Airport Schiphol' },
  { label: 'Dublin (DUB)', value: 'Dublin Airport' },
  { label: 'Brussels (BRU)', value: 'Brussels Airport' },
  { label: 'Copenhagen (CPH)', value: 'Copenhagen Airport' },
  // Major cities from Asia
  { label: 'Tokyo (HND)', value: 'Haneda Airport' },
  { label: 'Tokyo (NRT)', value: 'Narita International Airport' },
  { label: 'Seoul (ICN)', value: 'Incheon International Airport' },
  { label: 'Beijing (PEK)', value: 'Beijing Capital International Airport' },
  { label: 'Shanghai (PVG)', value: 'Shanghai Pudong International Airport' },
  { label: 'Mumbai (BOM)', value: 'Chhatrapati Shivaji Maharaj International Airport' },
  { label: 'Delhi (DEL)', value: 'Indira Gandhi International Airport' },
  { label: 'Bangkok (BKK)', value: 'Suvarnabhumi Airport' },
  { label: 'Singapore (SIN)', value: 'Changi Airport' },
  { label: 'Kuala Lumpur (KUL)', value: 'Kuala Lumpur International Airport' },
  { label: 'Hong Kong (HKG)', value: 'Hong Kong International Airport' },
];